# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-29 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=b'images/members/')),
            ],
        ),
    ]
