# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-29 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='member',
            name='lname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
